install.packages("fitdistrplus")
install.packages("lubridate")
install.packages("ggplot2")
install.packages("lme4")
install.packages("dplyr")
install.packages("DHARMa")
install.packages("mosaic")
install.packages("rsq")

library(mosaic)
library(ggplot2)
library(lme4)
library(dplyr)
library(DHARMa)
library(lubridate) #work with dates
library(fitdistrplus)
library(rsq)
